### PR TITLE
feat(config): add usage primary host pin

### PR DESCRIPTION
**Pull request by muqsitnawaz**
Adds a user-scope `usage.primary-host` key operated exclusively through `agents config`.

## What changed

- Registers `usage.primary-host` as `config.usagePrimaryHost` with device-name validation.
- Extends config parsing, formatting, storage hints, list/get/set/unset, and help examples.
- Exports `resolveUsagePrimaryHost()` with explicit pin → `interactive.host` → `null` resolution.
- Documents the semantic difference between the interactive and usage-primary hosts and adds a changelog fragment.

## Verification

No graphical UI surface; this changes CLI output and config storage. Run screenshot: `yosemite-s0:/home/muqsit/src/github.com/muqsitnawaz/agents-cli/.agents/scratch/usage-primary-config-run.png`. Uploaded text log: https://gist.github.com/muqsitnawaz/5dc7d80b659078ab87b6945b06d6befc

- `bun run test -- src/lib/config-keys.test.ts src/lib/device-config.test.ts src/commands/config.test.ts` — 63 passed.
- `bun run build` — passed.
- Real CLI `set → get → list → unset → get` flow — passed.

### CODE REVIEW

**Comment by muqsitnawaz** [comment]
APPROVE — non-author review complete. No blocking or non-blocking findings.

Evidence:
- Registry and validation: `apps/cli/src/lib/device-config.ts:124-136` declares the user-scope string key and calls `assertValidDeviceName`.
- Resolution: `apps/cli/src/lib/device-config.ts:434-438` is explicit override → interactive fallback → null.
- Grammar and metadata: `apps/cli/src/lib/config-keys.ts:148-150`, `:210-211`, `:232-235`, and `:274-277` cover parsing, formatting, known-key listing, and `config.usagePrimaryHost`.
- Operator path: `apps/cli/src/commands/config.ts:123-125`, `:170-173`, `:208-211`, and `:263-270` wire only `agents config` set/unset/get/list.
- Tests: `apps/cli/src/lib/device-config.test.ts:41-50` pins override/fallback/null; `apps/cli/src/commands/config.test.ts:77-84` pins set/get/unset/list.
- Docs: `apps/cli/docs/concepts.md:218-222` states the operator surface and resolution chain.

Focused review run:
- `config-keys.test.ts`: 21 passed.
- Direct `bun test` cannot execute the pre-existing device-config harness because `vi.resetModules is not a function` at `apps/cli/src/lib/device-config.test.ts:13`; every existing test in that file fails at the same shared helper, so this is not introduced by PR #2586.
- The combined command run timed out broadly on this loaded host, including unchanged tests such as `sets and gets a run model default`; this is not a PR-specific failure.

**Comment by muqsitnawaz** [comment]
## Independent review: APPROVED

**Verdict: non-blocking; no findings.**

Evidence reviewed:
- `apps/cli/src/lib/device-config.ts:124-136` registers `usage.primary-host` as `yamlKey: usagePrimaryHost`, `scope: user`, `type: string`, and validates through `assertValidDeviceName`.
- `apps/cli/src/lib/device-config.ts:434-438` resolves the explicit usage key, then `interactive.host`, then `null`.
- `apps/cli/src/lib/config-keys.ts:148-150` parses only the canonical key; `apps/cli/src/lib/config-keys.ts:210-211` formats it; `apps/cli/src/lib/config-keys.ts:232-235` lists it; `apps/cli/src/lib/config-keys.ts:274-277` maps it to `config.usagePrimaryHost`.
- `apps/cli/src/commands/config.ts:123-125`, `apps/cli/src/commands/config.ts:170-173`, and `apps/cli/src/commands/config.ts:208-211` wire set/unset/get through the registry-backed config API. `apps/cli/src/commands/config.ts:269-271` emits it from central config listing only when set.
- `apps/cli/src/commands/config.test.ts:77-84` exercises set/get/list/unset and verifies the unset key disappears from list output.
- `apps/cli/src/lib/device-config.test.ts:41-50` covers null default, interactive fallback, explicit override, and fallback restoration after unset.
- `apps/cli/docs/concepts.md:218-222` documents the config-only operator surface and resolution order.

I also checked the complete PR diff and surrounding config/device code against the repo conventions. The added `config-keys` cases pass under the direct focused run (21/21); the direct Bun runner cannot execute the pre-existing Vitest `vi.resetModules()` suite on this host, so CI remains the authoritative full-suite signal.

**Comment by muqsitnawaz** [comment]
APPROVE — non-author code review clear.

I found no blocking or non-blocking code issues. Evidence checked:

- `apps/cli/src/lib/device-config.ts:123-137` registers `usage.primary-host` as a validated user-scope string stored at `config.usagePrimaryHost`; `apps/cli/src/lib/device-config.ts:434-438` implements the documented explicit pin → `interactive.host` → `null` resolution.
- `apps/cli/src/commands/config.ts:119-126`, `170-173`, and `208-211` route set/unset/get through the canonical config registry, while `apps/cli/src/commands/config.ts:263-270` lists only persisted central values.
- `apps/cli/src/lib/config-keys.ts:145-149`, `177-181`, `207-212`, and `273-278` keep parsing, validation errors, formatting, and storage hints exhaustive for the new scope.
- `apps/cli/src/commands/config.test.ts:77-85`, `apps/cli/src/lib/config-keys.test.ts:55-58`, and `apps/cli/src/lib/device-config.test.ts:41-50` cover the real CLI round trip, grammar, and fallback precedence.
- `apps/cli/docs/concepts.md:215-222` and `apps/cli/.changelog/next/usage-primary-host.md:1-5` document the user-visible key and semantic distinction.

Scope is appropriately limited to the config track; downstream usage aggregation can consume the exported resolver without duplicating fallback policy. `bash scripts/verify-docs.sh` and `bash scripts/verify-command-index.sh` both pass locally. Merge remains contingent on required CI returning green.
